### ISSUE TITLE
HDMI CEC Support Version.

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-hdmi_cec#4]
The present References describe that the HAL should support CEC version 1.3a, but this needs to be changed to HDMI CEC 1.4b as per RDK requirements.  This now needs to be considered and any references to the CEC Version 1.3a should be removed.

**Comment by Ulrond** [comment]
@srinivasgtl  the description is a statement, what's the actual problem here? That needs to be fixed?

**Comment by srinivasgtl** [comment]
@Ulrond ,  updated with description.

**Comment by hari22yuva** [comment]
merged to develop
