### ISSUE TITLE
HDMI CEC Reference Section

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-hdmi_cec#9]
Update the reference section on the spec page:

For now it says 1.3a which should point to the right spec HDMI 1-4 SPEC

**Comment by hari22yuva** [comment]
Please check @krishna-1809 
https://github.com/rdkcentral/rdk-halif-hdmi_cec/issues/4
if you are not duplicating ?

**Comment by krishna-1809** [comment]
Yes this seems to be a duplicate of https://github.com/rdkcentral/rdk-halif-hdmi_cec/issues/4

**Comment by krishna-1809** [comment]
Duplicate of https://github.com/rdkcentral/rdk-halif-hdmi_cec/issues/4
